const { AllEventList, getCalEvent, createEvents, createEventActivityUser, handleIsGoing, handleinterested, getEventById,createPost, getPostById, getAllPost, deleteEventPost, updateEventPost, getAllUserPost, getAllInstitutePost, getAllPostByEvent, getFavEvent, getAllCommentsByPost, addLikes, addComment, checkPostLike, autogeneratedPostForInterested, deleteComment, generateEventPost, getAllInterestedPostByInstituteId, deleteMyEvent } = require("./events.controller");

const eventsRouterV2 =require("express").Router()


eventsRouterV2.get('/getCalEvent/:userId/:role' , getCalEvent) ;
eventsRouterV2.get('/getFavEvent/:userId/:role' , getFavEvent) ;
eventsRouterV2.get('/getEventById/:userId/:role/:eventId' , getEventById) ;
eventsRouterV2.post('/createEvents' , createEvents) ;
eventsRouterV2.post('/createEventActivityUser' , createEventActivityUser) ;


eventsRouterV2.post('/handleIsGoing/:userId/:role/:eventId' , handleIsGoing) ;
eventsRouterV2.post('/handleinterested/:userId/:role/:eventId' , handleinterested) ;
// eventsRouterV2.get('/getAllEvents' , AllEventList) ;


// all posts routes CRUD
eventsRouterV2.post('/createPost' , createPost);
eventsRouterV2.get('/getPostById/:id' , getPostById);
eventsRouterV2.delete('/deleteEventPost/:id' , deleteEventPost);
eventsRouterV2.delete('/deleteMyEvent/:id' , deleteMyEvent);
eventsRouterV2.put('/updateEventPost/:id' , updateEventPost);

// get post by different way
eventsRouterV2.get('/getAllPost' , getAllPost);
eventsRouterV2.get('/getAllUserPost/:userId/:role' , getAllUserPost);
eventsRouterV2.get('/getAllInstitutePost/:instituteId' , getAllInstitutePost);
eventsRouterV2.get('/getAllPostByEvent/:eventId' , getAllPostByEvent);

// post self like
eventsRouterV2.get('/checkPostLike/:postId/:userId/:role' , checkPostLike);


// COMMENTS ROUTES

eventsRouterV2.post('/addComment' , addComment);
eventsRouterV2.post('/addLikes' , addLikes);
eventsRouterV2.get('/getAllCommentsByPost/:postId' , getAllCommentsByPost);
eventsRouterV2.delete('/deleteComment/:id' , deleteComment);

// CREATE AUTO POST INTEREST
eventsRouterV2.post('/autogeneratedPostForInterested' , generateEventPost);


// GET POST BY INSTITUTE ID FOR INTERESTED USERS

eventsRouterV2.get('/getAllInterestedPostByInstituteId/:instituteId' , getAllInterestedPostByInstituteId);





module.exports = eventsRouterV2